//! Offline cryptographic license key verification.
//!
//! # Bounded Context: Licensing
//!
//! Owns key decoding, Ed25519 signature verification, expiry checks,
//! and claims extraction. No network dependencies — verification is
//! fully offline using the public key embedded at compile time.
//!
//! License keys are Ed25519-signed payloads containing customer info
//! and an expiry date. The binary embeds only the public key; forging
//! a valid key requires the private key, which never leaves the
//! issuing server.
//!
//! # Key format
//!
//! `base64(json_payload || 64-byte Ed25519 signature)`. The JSON
//! payload deserialises into [`LicenseClaims`].

use std::path::PathBuf;

use ed25519_dalek::{Signature, Verifier, VerifyingKey};
use serde::{Deserialize, Serialize};
use thiserror::Error;

use crate::constants::{CONFIG_DIR, ENV_LICENSE_KEY};

/// Length of an Ed25519 signature in bytes.
const SIGNATURE_LEN: usize = 64;

/// Ed25519 public key used to verify license keys.
///
/// **Placeholder.** Replace with the real public key generated by
/// `cargo run --example keygen`. The binary will not verify any key
/// until this constant is updated to a real keypair's public bytes.
///
/// Note: must NOT be all zeros (the Ed25519 identity point), which
/// would trivially verify any all-zero signature.
const PUBLIC_KEY_BYTES: [u8; 32] = [
    0xc1, 0x42, 0x9b, 0x1f, 0x8a, 0x7d, 0x55, 0x33, 0xe2, 0x90, 0x4c, 0xa8, 0x6f, 0x12, 0xd7, 0x3b,
    0x91, 0xae, 0x57, 0x60, 0xfe, 0x84, 0x2c, 0x05, 0x1d, 0x7e, 0xa3, 0xb4, 0x8c, 0x29, 0x66, 0x18,
];

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LicenseClaims {
    pub customer_name: String,
    pub customer_id: String,
    /// ISO 8601 date issued (YYYY-MM-DD).
    pub issued_at: String,
    /// ISO 8601 date when the key expires (YYYY-MM-DD).
    pub expires_at: String,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ExpiryStatus {
    Valid,
    ExpiringSoon { days: i64 },
    Expired,
}

#[derive(Error, Debug)]
pub enum LicenseError {
    #[error("invalid base64 encoding: {0}")]
    InvalidBase64(#[from] base64::DecodeError),
    #[error("key too short to contain a signature")]
    TooShort,
    #[error("invalid signature")]
    InvalidSignature,
    #[error("invalid public key (compile-time key is malformed)")]
    InvalidPublicKey,
    #[error("failed to parse license claims: {0}")]
    InvalidClaims(#[from] serde_json::Error),
    #[error("invalid expiry date format (expected YYYY-MM-DD): {0}")]
    InvalidDate(String),
    #[error("io error on {path}: {source}")]
    Io {
        path: String,
        #[source]
        source: std::io::Error,
    },
}

/// Verify a license key against the embedded public key.
pub fn verify_license_key(key: &str) -> Result<LicenseClaims, LicenseError> {
    verify_license_key_with(key, &PUBLIC_KEY_BYTES)
}

/// Verify a license key against an arbitrary public key. Test-only
/// hook so integration tests can round-trip sign→verify without baking
/// a real production key into the binary.
pub fn verify_license_key_with(
    key: &str,
    public_key: &[u8; 32],
) -> Result<LicenseClaims, LicenseError> {
    use base64::Engine;
    let bytes = base64::engine::general_purpose::STANDARD.decode(key.trim())?;

    if bytes.len() <= SIGNATURE_LEN {
        return Err(LicenseError::TooShort);
    }

    let (payload, sig_bytes) = bytes.split_at(bytes.len() - SIGNATURE_LEN);
    let signature = Signature::from_slice(sig_bytes).map_err(|_| LicenseError::InvalidSignature)?;

    let verifying_key =
        VerifyingKey::from_bytes(public_key).map_err(|_| LicenseError::InvalidPublicKey)?;

    verifying_key
        .verify(payload, &signature)
        .map_err(|_| LicenseError::InvalidSignature)?;

    let claims: LicenseClaims = serde_json::from_slice(payload)?;
    Ok(claims)
}

/// Determine whether a license is currently valid, expiring soon, or
/// expired. `Soon` is anything within 30 days.
pub fn check_expiry(claims: &LicenseClaims) -> Result<ExpiryStatus, LicenseError> {
    let expires = parse_date(&claims.expires_at)?;
    let today = today_ymd();
    let days_remaining = days_between(today, expires);

    if days_remaining < 0 {
        Ok(ExpiryStatus::Expired)
    } else if days_remaining <= 30 {
        Ok(ExpiryStatus::ExpiringSoon {
            days: days_remaining,
        })
    } else {
        Ok(ExpiryStatus::Valid)
    }
}

/// Path on disk where chronikl looks for an activated license key.
///
/// `~/.config/chronikl/license.key` on Linux/macOS, the equivalent
/// XDG / platform path elsewhere via `dirs::config_dir()`.
pub fn license_path() -> Option<PathBuf> {
    dirs::config_dir().map(|d| d.join(CONFIG_DIR).join("license.key"))
}

/// Resolve a license key from (in order): env var, disk file. Returns
/// `None` when neither is set.
pub fn resolve_key() -> Option<String> {
    if let Ok(key) = std::env::var(ENV_LICENSE_KEY)
        && !key.trim().is_empty()
    {
        return Some(key);
    }
    let path = license_path()?;
    let bytes = std::fs::read_to_string(path).ok()?;
    let trimmed = bytes.trim();
    if trimmed.is_empty() {
        None
    } else {
        Some(trimmed.to_string())
    }
}

/// Verify whatever key is currently configured. Returns `Some(claims)`
/// when a valid, non-expired key is in place; `None` for "no license"
/// or "license invalid" — callers that want detail should call
/// [`resolve_key`] + [`verify_license_key`] + [`check_expiry`] manually.
pub fn current_claims() -> Option<LicenseClaims> {
    let key = resolve_key()?;
    let claims = verify_license_key(&key).ok()?;
    let status = check_expiry(&claims).ok()?;
    if status == ExpiryStatus::Expired {
        None
    } else {
        Some(claims)
    }
}

/// Persist a verified license key to the standard on-disk location.
pub fn write_to_disk(key: &str) -> Result<PathBuf, LicenseError> {
    let path = license_path().ok_or_else(|| LicenseError::Io {
        path: "<config_dir>".into(),
        source: std::io::Error::other("no config dir available on this platform"),
    })?;
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent).map_err(|e| LicenseError::Io {
            path: parent.display().to_string(),
            source: e,
        })?;
    }
    std::fs::write(&path, key.trim()).map_err(|e| LicenseError::Io {
        path: path.display().to_string(),
        source: e,
    })?;
    Ok(path)
}

/// Remove the on-disk license key, if any. Returns `Ok(true)` when a
/// file was removed, `Ok(false)` when there was nothing to remove.
pub fn remove_from_disk() -> Result<bool, LicenseError> {
    let path = match license_path() {
        Some(p) => p,
        None => return Ok(false),
    };
    if !path.exists() {
        return Ok(false);
    }
    std::fs::remove_file(&path).map_err(|e| LicenseError::Io {
        path: path.display().to_string(),
        source: e,
    })?;
    Ok(true)
}

// ── Minimal date helpers (avoid pulling in chrono just for this) ────

type Ymd = (i64, i64, i64);

fn parse_date(s: &str) -> Result<Ymd, LicenseError> {
    let parts: Vec<&str> = s.split('-').collect();
    if parts.len() != 3 {
        return Err(LicenseError::InvalidDate(s.to_string()));
    }
    let y = parts[0]
        .parse::<i64>()
        .map_err(|_| LicenseError::InvalidDate(s.to_string()))?;
    let m = parts[1]
        .parse::<i64>()
        .map_err(|_| LicenseError::InvalidDate(s.to_string()))?;
    let d = parts[2]
        .parse::<i64>()
        .map_err(|_| LicenseError::InvalidDate(s.to_string()))?;
    Ok((y, m, d))
}

fn today_ymd() -> Ymd {
    let secs = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap()
        .as_secs() as i64;
    epoch_secs_to_ymd(secs)
}

/// Howard Hinnant's civil_from_days algorithm.
fn epoch_secs_to_ymd(secs: i64) -> Ymd {
    let mut days = secs / 86400;
    if secs < 0 && secs % 86400 != 0 {
        days -= 1;
    }
    days += 719468;
    let era = if days >= 0 { days } else { days - 146096 } / 146097;
    let doe = days - era * 146097;
    let yoe = (doe - doe / 1460 + doe / 36524 - doe / 146096) / 365;
    let y = yoe + era * 400;
    let doy = doe - (365 * yoe + yoe / 4 - yoe / 100);
    let mp = (5 * doy + 2) / 153;
    let d = doy - (153 * mp + 2) / 5 + 1;
    let m = if mp < 10 { mp + 3 } else { mp - 9 };
    let y = if m <= 2 { y + 1 } else { y };
    (y, m, d)
}

fn days_between(a: Ymd, b: Ymd) -> i64 {
    ymd_to_epoch_days(b) - ymd_to_epoch_days(a)
}

fn ymd_to_epoch_days(date: Ymd) -> i64 {
    let (mut y, m, d) = date;
    if m <= 2 {
        y -= 1;
    }
    let era = if y >= 0 { y } else { y - 399 } / 400;
    let yoe = y - era * 400;
    let doy = (153 * (if m > 2 { m - 3 } else { m + 9 }) + 2) / 5 + d - 1;
    let doe = yoe * 365 + yoe / 4 - yoe / 100 + doy;
    era * 146097 + doe - 719468
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parse_valid_date() {
        assert_eq!(parse_date("2026-12-31").unwrap(), (2026, 12, 31));
    }

    #[test]
    fn parse_invalid_date() {
        assert!(parse_date("not-a-date").is_err());
        assert!(parse_date("2026/12/31").is_err());
    }

    #[test]
    fn days_between_one_day() {
        assert_eq!(days_between((2026, 2, 13), (2026, 2, 14)), 1);
        assert_eq!(days_between((2026, 2, 14), (2026, 2, 13)), -1);
    }

    #[test]
    fn epoch_round_trip() {
        let ymd = (2026, 5, 8);
        let days = ymd_to_epoch_days(ymd);
        assert_eq!(epoch_secs_to_ymd(days * 86400), ymd);
    }

    #[test]
    fn expiry_far_future_is_valid() {
        let claims = LicenseClaims {
            customer_name: "x".into(),
            customer_id: "x".into(),
            issued_at: "2026-01-01".into(),
            expires_at: "2099-12-31".into(),
        };
        assert_eq!(check_expiry(&claims).unwrap(), ExpiryStatus::Valid);
    }

    #[test]
    fn expiry_long_past_is_expired() {
        let claims = LicenseClaims {
            customer_name: "x".into(),
            customer_id: "x".into(),
            issued_at: "2020-01-01".into(),
            expires_at: "2020-12-31".into(),
        };
        assert_eq!(check_expiry(&claims).unwrap(), ExpiryStatus::Expired);
    }

    #[test]
    fn expiry_within_30_days_flags_soon() {
        let today = today_ymd();
        let future_days = ymd_to_epoch_days(today) + 15;
        let f = epoch_secs_to_ymd(future_days * 86400);
        let claims = LicenseClaims {
            customer_name: "x".into(),
            customer_id: "x".into(),
            issued_at: "2026-01-01".into(),
            expires_at: format!("{:04}-{:02}-{:02}", f.0, f.1, f.2),
        };
        match check_expiry(&claims).unwrap() {
            ExpiryStatus::ExpiringSoon { days } => assert!((0..=30).contains(&days)),
            other => panic!("expected ExpiringSoon, got {other:?}"),
        }
    }

    #[test]
    fn verify_rejects_garbage() {
        assert!(verify_license_key("not valid base64!!!").is_err());
    }

    #[test]
    fn verify_rejects_too_short() {
        use base64::Engine;
        let short = base64::engine::general_purpose::STANDARD.encode(b"tiny");
        assert!(matches!(
            verify_license_key(&short),
            Err(LicenseError::TooShort)
        ));
    }

    #[test]
    fn verify_rejects_unsigned_payload() {
        // 100-byte payload + 64 zero bytes that look like a signature.
        // Should fail at signature verification (zero sig is not valid
        // for the placeholder key).
        use base64::Engine;
        let payload = br#"{"customer_name":"X","customer_id":"x","issued_at":"2026-01-01","expires_at":"2099-12-31"}"#;
        let mut blob = payload.to_vec();
        blob.extend_from_slice(&[0u8; 64]);
        let encoded = base64::engine::general_purpose::STANDARD.encode(&blob);
        assert!(verify_license_key(&encoded).is_err());
    }
}
